print(try{
    5
}.except(){e>>>
    print("except", type(e))
}.run()
)
